config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :professors

  resources :posts do
  	resources :comments
	end

  post "posts/:id" => "posts#upvote"
  root to: "application#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :professor
  belongs_to :user

  has_many :comments, dependent: :destroy

  has_many :votes, dependent: :destroy
  has_many :upvoted_users, through: :votes, source: :user

  extend FriendlyId
  friendly_id :text, use: :slugged
end

app/models/professor.rb
class Professor < ActiveRecord::Base
	has_many :posts
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", icon: "30x30>" }, default_url: "/images/:style/professor.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy

  has_many :comments, dependent: :destroy

  has_many :votes, dependent: :destroy
  has_many :upvoted_posts, through: :votes, source: :post

  extend FriendlyId
  friendly_id :username, use: :slugged

  attr_accessor :login

  validates :username,
  :presence => true,
  :uniqueness => { :case_sensitive => false }

	validate :validate_username

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

	def validate_username
	  if User.where(email: username).exists?
	    errors.add(:username, :invalid)
	  end
	end
		
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    @prof = Professor.all
    @users = User.all
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
  
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
	  @post = Post.friendly.find(params[:post_id])
	  @comment = @post.comments.create(comment_params)
	  @comment.user_id = current_user.id
	  if @comment.save
	    redirect_to @post
	  else
	    flash.now[:danger] = "error"
	  end
	end

	def destroy
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to @post
  end

	private

    def comment_params
      params.require(:comment).permit(:text, :user_id, :post_id)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
		@post = Post.all
  end

  def show
		@post = Post.friendly.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.friendly.find(params[:id])
    unless current_user == @post.user_id || current_user.try(:admin?)
      redirect_to @post 
      flash[:alert] = "You don't have permission to edit this post."
    end
  end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully removed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @post = Post.friendly.find(params[:id])

    if current_user
      if @post.votes.create(user_id: current_user.id).id
        flash[:notice] =  "Thank you for upvoting!"
        redirect_to(posts_path)
      else 
        flash[:notice] =  "You have already upvoted this!"
        redirect_to(posts_path)
      end
    else
      redirect_to(posts_path)
    end
  end
  helper_method :upvote


  private
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:text, :upvote, :user_id, :professor_id, :slug)
    end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
	before_action :set_professor, only: [:show, :edit, :update, :destroy]

  def index
		@professor = Professor.all
  end

  def show
		@professor = Professor.friendly.find(params[:id])
  end

  def new
    @professor = Professor.new
  end

  def edit
    unless current_user.try(:admin?)
      redirect_to @professor 
      flash[:alert] = "You don't have permission to edit this professor."
    end
  end

  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'professor was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_professor
      @professor = Professor.friendly.find(params[:id])
    end

    def professor_params
      params.require(:professor).permit(:name, :slug, :avatar)
    end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  def new
  end

  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def index
    unless can? :manage, @user
      redirect_to root_path
      flash[:alert] = "You don't have permission to view all users."
    end
  	@users = User.all
  end

  def show
  	@user = User.friendly.find(params[:id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	def create
		
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/application/index.html.erb
<hr>
<div class="expanded button-group">
	<%= link_to "View all Posts", posts_path, class: "hollow button" %>
	<%= link_to "View all Professors", professors_path, class: "hollow button" %>
	<%= link_to "Add a new Post", new_post_path, class: "hollow button" %>
	<%= link_to "Add a new Professor", new_professor_path, class: "hollow button" %>
</div>
<hr>
<br>

app/views/comments/_new.html.erb
<% if current_user %>
	<%= form_for([@post, @post.comments.new]) do |f| %>
	  <div class>
	    <%= f.text_area :text, placeholder: 'submit a comment' %>
	    <%= f.submit 'Save', class: "button hollow" %>
	  </div>
	<% end %>
<% end %>

app/views/comments/_show.html.erb
<% if (@post.comments.count > 0) %>
	<% @post.comments.each do |c| %>
	  <hr>
	  <p>
	    <%= link_to User.find(c.user_id).username, user_path(User.friendly.find(c.user_id))%> : <%= c.text %>
	    <% if current_user %>
				<% if current_user.id == c.user_id %>
  				<%= link_to 'Delete', [c.post, c], data: { confirm: 'Are you sure?' }, :method => :delete %>
  			<% end %>
			<% end %>
		</p>
	<% end %>
<% else %>
	This post has no comments yet.
<% end %>

app/views/layouts/_footer.html.erb
	<footer class="footer">
	  <div class="row">
	    <div class="large-9 columns">
				<p>
					Page still under the development. Want to add to it? <a class="fa fa-github" target="_blank" href="https://github.com/arddit/myprofsays/"> Fork it!</a>
				</p>
	    </div>
	    <div class="large-3 columns">
        <p> 
        	&copy; Copyright <a class="fa" target="_blank" href="https://arddit.com/"> Ardit Hamzai</a>
        </p>
	    </div>
	  </div>
	</footer>

app/views/layouts/_header.html.erb
<nav class="top-bar hide-for-small expanded button-group">
	<a href="/"><div class="top-bar-title">
		<span class="badge">M</span> 
		<span class="badge">Y</span> 
		<span class="success badge">P</span> 
		<span class="success badge">R</span> 
		<span class="success badge">O</span> 
		<span class="success badge">F</span> 
		<span class="success badge">E</span> 
		<span class="success badge">S</span> 
		<span class="success badge">S</span> 
		<span class="success badge">O</span> 
		<span class="success badge">R</span> 
		<span class="alert badge">S</span> 
		<span class="alert badge">A</span> 
		<span class="alert badge">Y</span> 
		<span class="alert badge">S</span>
	</div></a>
  <div class="top-bar-right">
	  <% if user_signed_in? %> 
	  <ul class="menu">
	  	<li><%= link_to "Home",  root_path, class: "button" %></li>
			<li><%= link_to "Profile", user_path(current_user), class: "success button" %></li> 
			<li><%= link_to "Settings", edit_user_registration_path(current_user), class: "alert button" %></li>
			<li><%= link_to "Log out", destroy_user_session_path, method: "delete", class: "warning button" %></li>
		</ul>
		<% else %>
		<div class="menu">
			<li><%= link_to "Home", root_path, class: "button" %></li>
			<li><%= link_to "Log In", new_user_session_path, class: "success button" %></li>
			<li><%= link_to "Sign Up", new_user_registration_path, class: "alert button" %></li> 
		</ul>
		<% end %>
	</div>
</nav>
<% if current_page?('/') %>
<br>
	<footer class="footer">
	  <div class="row full-width">
	    <div class="small-2 medium-2 large-2 columns">
	    	<i class="fa fa-comments-o"></i>
	    </div>
	    <div class="small-22 medium-4 large-6 columns">
				<h3>
					Welcome to My Professor Says
				</h3>
				<p>
					Gather around and think of all the witty remarks and fond memories.
				</p>
	    </div>
	    <div class="small-6 medium-3 large-2 columns">
	      <h4> Contact Me</h4>
	      <ul class="footer-links">
	        <li><a class="fa fa-envelope" href="mailto:ardihamza@gmail.com"> Email</a></li>
	        <li><a class="fa fa-laptop" target="_blank" href="http://arddit.com/"> arddit.com</a></li>
	      <ul>
	    </div>
	    <div class="small-6 medium-3 large-2 columns">
	      <h4>Follow Me</h4>
	      <ul class="footer-links">
	        <li><a class="fa fa-github" target="_blank" href="https://github.com/arddit"> GitHub</a></li>
	        <li><a class="fa fa-twitter" target="_blank" href="https://twitter.com/arrddit"> Twitter</a></li>
	      <ul>
	    </div>
	  </div>
	</footer>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title> My Professor Says </title>
    <link rel="shortcut icon" href="http://contributors.rubyonrails.org/assets/favicon-e64b20ad4e794fd9a33bb947feb54b43467b288fb364221f06acb5ad73ddd9cc.ico">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="wrapper">
      <div id="header">
        <%= render 'layouts/header' %>
      </div>
      <%= render 'layouts/messages' %>
      <div id="content">
        <div class="row">
          <%= yield %>
        </div>
      </div>
      <div id="footer">
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
	  <dvi class="row">
			<div class="button-group">
				<%= link_to " Back to all Posts", posts_path, class: "button hollow fi-arrow-left"%>
				<%= link_to " Add a new Professor", new_professor_path, class: "button hollow fi-plus" %>
			</div>
		</dvi>

	  <% if current_user %>
	  <h3>Edit Post</h3>
			<%= form_for(@post) do |f| %>

			<div class="field">
	      <p><%= f.label :text%>
	      <%= f.text_field :text, autofocus: true %></p>
	    </div>

	    <div class="field">
	      <p><%= f.label :professor_id%>
	      <%= f.collection_select :professor_id, Professor.all, :id, :name, autofocus: true %>
	      <%= link_to "Add a new Professor", new_professor_path %></p>
	    </div>

	    <br>
	    <div class="actions">
	      <p><%= f.submit "Save changes", class: "success expanded button" %></p>
	    </div>

			<% end %>
		<% else %>
			<h4>Please <%= link_to "Log In", new_user_session_path %> or <%= link_to "Create an Account", new_user_registration_path %> to add a new post.</h4>
			
		<% end %>
	</div>
</div>

app/views/posts/index.html.erb
<dvi class="row">
	<div class="button-group">
		<%= link_to " Add a new Post", new_post_path, class: "button hollow fi-plus" %>
		<%= link_to " Add a new Professor", new_professor_path, class: "button hollow fi-plus" %>
		</div>
</dvi>
<% @post.each do |p| %>
	<h4>"<%= link_to p.text, p %>"</h4>
<p>Professor:   
			<%= link_to (image_tag (Professor.find(p.professor_id).avatar.url(:icon))), professor_path(Professor.find(p.professor_id)) %>
			<%= link_to Professor.find(p.professor_id).name, professor_path(Professor.friendly.find(p.professor_id)) %>
	| by <%= link_to User.find(p.user_id).username, user_path(User.friendly.find(p.user_id))%>
	| upvotes: <%= p.votes.count %>
	| <%= link_to "comments:", p %> <%= p.comments.count %></p>
	<% if current_user %>
		<% if current_user.id == p.user_id || (can? :manage, p) %>
	  	<p><%= link_to 'Edit', edit_post_path(p) %>
	  	<%= link_to 'Delete', p, method: :delete, data: { confirm: 'Are you sure?' }%></p>
	  <% end %>
	  <%= link_to 'Upvote', p, method: :upvote, class: "success button hollow fa fa-arrow-circle-up"%>
	<% end %>
	<hr>
<% end %>

app/views/posts/new.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
	  <dvi class="row">
			<div class="button-group">
				<%= link_to " Back to all Posts", posts_path, class: "button hollow fi-arrow-left"%>
				<%= link_to " Add a new Professor", new_professor_path, class: "button hollow fi-plus" %>
			</div>
		</dvi>

	  <% if current_user %>
	  <h3>New Post</h3>
			<%= form_for(@post) do |f| %>

			<div class="field">
	      <p><%= f.label :text%>
	      <%= f.text_field :text, autofocus: true %></p>
	    </div>

	    <div class="field">
	      <p><%= f.label :professor_id%>
	      <%= f.collection_select :professor_id, Professor.all, :id, :name, autofocus: true %>
	      <%= link_to "Add a new Professor", new_professor_path %></p>
	    </div>

	    <br>
	    <div class="actions">
	      <p><%= f.submit "Submit Post", class: "success expanded button" %></p>
	    </div>

			<% end %>
		<% else %>
			<h4>Please <%= link_to "Log In", new_user_session_path %> or <%= link_to "Create an Account", new_user_registration_path %> to add a new post.</h4>
			
		<% end %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="row">
	<div class="button-group">
		<%= link_to " Back to All Posts", posts_path, class: "button hollow fi-arrow-left"%>
		<%= link_to " Add a new Post", new_post_path, class: "button hollow fi-plus" %>
		</div>
</div>
<br>
<h4>"<%= @post.text %>"</h4> 
<p>Professor:  
			<%= link_to (image_tag (Professor.find(@post.professor_id).avatar.url(:icon))), professor_path(Professor.find(@post.professor_id)) %>
			<%= link_to Professor.find(@post.professor_id).name, professor_path(Professor.friendly.find(@post.professor_id)) %>
	| by <%= link_to User.find(@post.user_id).username, user_path(User.friendly.find(@post.user_id))%>
	| upvotes: <%= @post.votes.count %></p>

<% if current_user %>
	<% if current_user.id == @post.user_id %>
  	<p><%= link_to 'Edit', edit_post_path(@post) %>
  	<%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }%></p>
  <% end %>
  <%= link_to 'Upvote', @post, method: :upvoted, class: "success button hollow fa fa-arrow-circle-up" %>

<% else %>
	Please <%= link_to "Log In", new_user_session_path %> or <%= link_to "Create an Account", new_user_registration_path %> to upvote and comment posts.
<% end %>

<br>
<br>
<p>Comments:</p>
<%= render "comments/show" %>

<%= render "comments/new" %>


<hr>

app/views/professors/edit.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
	  <dvi class="row">
			<div class="button-group">
				<%= link_to " Back to all Professors", professors_path, class: "button hollow fi-arrow-left"%>
				<%= link_to " Add a new Post", new_post_path, class: "button hollow fi-plus" %>
			</div>
		</dvi>

	  <% if current_user %>
	  <h3>Eddit professor</h3>
			<%= form_for(@professor) do |f| %>

			<div class="field">
	      <p><%= f.label :name%>
	      <%= f.text_field :name, autofocus: true %></p>
	    </div>

	    <div class="field">
	      <p>Upload an image:
	      <%= f.file_field :avatar, class: "hollow button secondary" %></p>
	    </div>

	    <br>
	    <div class="actions">
	      <p><%= f.submit "Save changes", class: "success expanded button" %></p>
	    </div>

			<% end %>
		<% else %>
			<h4>Please <%= link_to "Log In", new_user_session_path %> or <%= link_to "Create an Account", new_user_registration_path %> to add a new professor.</h4>
			
		<% end %>
	</div>
</div>

app/views/professors/index.html.erb
<dvi class="row">
	<div class="button-group">
		<%= link_to " Back to all Posts", posts_path, class: "button hollow fi-arrow-left"%>
		<%= link_to " Add a new Professor", new_professor_path, class: "button hollow fi-plus" %>
		</div>
</dvi>

<h4>All professors:</h4>
<br>


<% @professor.each do |p| %>
	<p>
		<%= link_to (image_tag (p.avatar.url(:thumb))), professor_path(p) %>
		<%= link_to p.name, professor_path(p) %>
	</p>
	<hr>
<% end %>

app/views/professors/new.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
	  <dvi class="row">
		<div class="button-group">
			<%= link_to " Back to all Professors", professors_path, class: "button hollow fi-arrow-left"%>
			<%= link_to " Add a new Post", new_post_path, class: "button hollow fi-plus" %>
		</div>
	</dvi>

	  <% if current_user %>
	  <h3>Add a professor</h3>
			<%= form_for(@professor) do |f| %>

			<div class="field">
	      <p><%= f.label :name%>
	      <%= f.text_field :name, autofocus: true %></p>
	    </div>

	    <div class="field">
	      <p>Upload an image:
	      <%= f.file_field :avatar, class: "hollow button secondary" %></p>
	    </div>

	    <br>
	    <div class="actions">
	      <p><%= f.submit "Add Professor", class: "success expanded button" %></p>
	    </div>

			<% end %>
		<% else %>
			<h4>Please <%= link_to "Log In", new_user_session_path %> or <%= link_to "Create an Account", new_user_registration_path %> to add a new professor.</h4>
			
		<% end %>
	</div>
</div>

app/views/professors/show.html.erb
<dvi class="row">
	<div class="button-group">
		<%= link_to " Back to all Professors", professors_path, class: "button hollow fi-arrow-left"%>
		<%= link_to " Add a new Professor", new_professor_path, class: "button hollow fi-plus" %>
		</div>
</dvi>
<br>
<div class="row" style="text-align: center;">
	<h4><%= @professor.name %> </h4>
	<%= link_to (image_tag (@professor.avatar.url(:medium))), professor_path(@professor), class: "button hollow" %>
</div>
<hr>

<% if @professor.posts.count > 0 %>
	<% Post.where(professor_id: @professor.id).find_each do |p| %>
		<h4>"<%= link_to p.text, p %>"</h4>

		<p>Professor: 
			<%= link_to (image_tag (@professor.avatar.url(:icon))), professor_path(@professor) %>
			<%= link_to Professor.find(p.professor_id).name, professor_path(Professor.friendly.find(p.professor_id)) %>
			| by <%= link_to User.find(p.user_id).username, user_path(User.friendly.find(p.user_id))%>
			| upvotes: <%= p.votes.count %>
			| <%= link_to "comments:", p %> <%= p.comments.count %></p>
		<% if current_user %>
			<% if current_user.id == p.user_id %>
		  	<p><%= link_to 'Edit', edit_post_path(p) %>
		  	<%= link_to 'Delete', p, method: :delete, data: { confirm: 'Are you sure?' }%></p>
		  <% end %>
		  <%= link_to 'Upvote', p, method: :upvote, class: "success button large hollow fa fa-arrow-circle-up fa-5x"%>
		<% else %>
			Please <%= link_to "Log In", new_user_session_path %> or <%= link_to "Create an Account", new_user_registration_path %> to upvote posts.
		<% end %>
		<hr>
	<% end %>
<% else %>
	<h3>This professor has no posts yet.</h3>
<% end %>
<br>
<br>

app/views/users/index.html.erb
<dvi class="row">
	<div class="button-group">
		<%= link_to " Back to all Posts", posts_path, class: "button hollow fi-arrow-left"%>
		<%= link_to " Add a new Post", new_post_path, class: "button hollow fi-plus" %>
		</div>
</dvi>

<h4>All users:</h4>
<br>


<% @users.each do |u| %>
	<p>
		<%= link_to "#{u.username}", user_path(u) %>
		<% if u.admin? %>
			Is admin.
		<% else %>
			Not admin
		<% end %>
	</p>
	<hr>
<% end %>

app/views/users/show.html.erb
<div class="row">
	<div class="button-group">
		<%= link_to " Back to All Posts", posts_path, class: "button hollow fi-arrow-left"%>
		<%= link_to " Add a new Post", new_post_path, class: "button hollow fi-plus" %>
		</div>
</div>

<br>
<h4>Posts by <%= @user.username %></h4>
<hr>

<% if @user.posts.count > 0 %>
	<% Post.where(user_id: @user.id).find_each do |p| %>
		<h4>"<%= link_to p.text, p %>"</h4>

		<p>Professor:   
			<%= link_to (image_tag (Professor.find(p.professor_id).avatar.url(:icon))), professor_path(Professor.find(p.professor_id)) %>
			<%= link_to Professor.find(p.professor_id).name, professor_path(Professor.friendly.find(p.professor_id)) %>
			| by <%= link_to User.find(p.user_id).username, user_path(User.friendly.find(p.user_id))%>
			| upvotes: <%= p.votes.count %>
			| <%= link_to "comments:", p %> <%= p.comments.count %></p>
		<% if current_user %>
			<% if current_user.id == p.user_id %>
		  	<p><%= link_to 'Edit', edit_post_path(p) %>
		  	<%= link_to 'Delete', p, method: :delete, data: { confirm: 'Are you sure?' }%></p>
		  <% end %>
		  <%= link_to 'Upvote', p, method: :upvote, class: "success button large hollow fa fa-arrow-circle-up fa-5x"%>
		<% else %>
			Please <%= link_to "Log In", new_user_session_path %> or <%= link_to "Create an Account", new_user_registration_path %> to upvote or comment on posts.
		<% end %>
		<hr>
	<% end %>
<% else %>
	<h3>This user has no posts.</h3>
<% end %>

<h4>Comments by <%= @user.username %></h4>
<hr>

<% if @user.comments.count > 0 %>
	<% Comment.where(user_id: @user.id).find_each do |c| %>
		<p>"<%= c.text %>" | On: <%= link_to Post.find(c.post_id).text, post_path(Post.friendly.find(c.post_id)) %></p>
		<% if current_user %>
			<% if current_user.id == c.user_id %>
		  	<%= link_to 'Delete', [c.post, c], data: { confirm: 'Are you sure?' }, :method => :delete %>
		  <% end %>
		<% end %>
		<hr>
	<% end %>
<% else %>
	<p>This user has no comments.</p>
<% end %>
<br>
<br>